122/refact remover classe e transformar em funcao service hiring process request
aceleradora-TW/acelera-mais-api pull request #129
Opened 2022-01-17 16:52 UTC by estherwl

#122 - refact remover classe e transformar em funcao service hiring process request
====
  
### 🆙 CHANGELOG

- A classe HiringProcessRequest foi tranformada na função hiringProcessRequest

## ⚠️ Me certifico que:

- [ ] Não deixei nenhum novo warning, erro ou console.log nas minhas modificações
- [ ] Fiz deploy para ambiente de teste certificando que o build não quebrou
- [ ] Solicitei **code review** para 2 pessoas
- [ ] Solicitei **QA** para 2 pessoas
- [ ] Obtive aprovação de QA e posso fazer merge

## ⚠️ Como testar:

- [ ] Abrir URL da aplicação de teste: https://esther-acelera-mais.herokuapp.com/
- [ ] Fazer login (email:ju@gmail.com, senha: 123456)
- [ ] Criar movo processo seletivo
- [ ] Verificar se o processo foi criado e aparece corretamente
- [ ] Aplicação não deve conter nenhum erro, warning ou console.log
- [ ] Alteração proposta no card foi implementada

2022-01-17 17:17 UTC, narukaioh requested changes

2022-01-17 17:17 UTC, narukaioh commented on src/controllers/exercise/index.ts
> +    const result = await allExercises.getAllExercises({ page, count, hiringProcessId, type })
mesma coisa que falei no PR da Carol, se tem a necessidade de trocar o nome da variavel, entao vc pode substituir isso por 

```javascript
const result = await exerciseService().getAllExercises({ page, count, hiringProcessId, type })
 ```

2022-01-17 17:36 UTC, narukaioh requested changes

2022-01-17 17:36 UTC, narukaioh commented on src/controllers/hiring-process/index.ts
> +    const hiringProcessRequest = hiringRequest.convertFromHttpBody(request.body)
A mesma coisa pra esse fato aqui tb

2022-01-17 17:58 UTC, estherwl commented on src/controllers/hiring-process/index.ts
> +    const hiringProcessRequest = hiringRequest.convertFromHttpBody(request.body)
a gente mudou para 
const hiringProcess = hiringProcessRequest().convertFromHttpBody(request.body)
const result = await hiringService.createHiringProcessService(hiringProcess)
pq ao colocar const hiringProcessRequest = hiringProcessRequest().convert... aparece um erro "Block-scoped variable 'hiringProcessRequest' used before its declaration"

2022-01-17 18:50 UTC, ccarolb commented on src/controllers/hiring-process/index.ts
> +    const result = await hiringService.createHiringProcessService(hiringProcess)
aqui pode chamar hiringProcessService() direto também, e acredito que na linha seguinte tb dá pra fazer o mesmo com a função httpResponseHandler() @narukaioh

2022-01-18 12:49 UTC, estherwl commented on src/controllers/hiring-process/index.ts
> +    const result = await hiringService.createHiringProcessService(hiringProcess)
alterações feitas

2022-01-18 13:23 UTC, narukaioh approved these changes

2022-01-20 14:19 UTC, merged