132/trocar dominio exercise para challenge
aceleradora-TW/acelera-mais-api pull request #134
Opened 2022-02-07 18:46 UTC by Cibely87

#132/trocar dominio exercise para challenge
====

### 🆙 CHANGELOG

- [ ] Foi feita a troca dos nomes (domínio) Exercise por Challenge no backend
- [ ] No frontend, também foi realizada essa mudança de domínio.
- [ ] Alteração nos textos de layout que estão no front, como por exemplo o título Exercícios para Desafios

## ⚠️ Me certifico que:

- [ ] Não deixei nenhum novo warning, erro ou console.log nas minhas modificações
- [ ] Fiz deploy para ambiente de teste certificando que o build não quebrou
- [ ] Solicitei **code review** para 2 pessoas
- [ ] Solicitei **QA** para 2 pessoas
- [ ] Obtive aprovação de QA e posso fazer merge

## ⚠️ Como testar:

- [ ] Acessar link de teste: https://teste-cibely-acelera-mais-api.herokuapp.com/
- [ ] Fazer login (e-mail: ju@gmail.com, senha: 123456)
- [ ] Criar um novo processo, inserir planilha de candidatas e desafios
(candidatas: https://docs.google.com/spreadsheets/d/172hDo1RvIFpczFvuq3HoAD5wQoB2hBmnBHMoo_MYw8Y/edit#gid=199214593
exercícios: https://docs.google.com/spreadsheets/d/1Xn-fcGHuyx4TxzMCqTJ7gmKcMbMdNWR6CBtRHr2v84M/edit#gid=1886435917)
- [ ] Clicar no botões e verificar se eles mantém a funcionalidade proposta
- [ ] Aplicação não deve conter nenhum erro, warning ou console.log
- [ ] Alteração proposta no card foi implementada

2022-02-08 02:04 UTC, narukaioh requested changes

2022-02-08 02:04 UTC, narukaioh commented on src/controllers/candidate/index.ts
> +    return date
isso aqui é um problema, nao pode deixar retornando "date"

2022-02-08 02:04 UTC, narukaioh commented on src/controllers/challenge/index.ts
> +    return date
isso aqui tb foi deixado para trás, tem q retornar pro jeito q tava antes

2022-02-08 02:04 UTC, narukaioh commented on src/models/entity/Evaluation.ts
> +  exercise: Challenge;
aqui ta como exercise, deveria ser Challenge

2022-02-08 02:04 UTC, narukaioh commented on src/models/entity/HiringProcess.ts
> +  exercises: Challenge[]
aqui tb ta como `exercises` deveria ser `challlenges`

2022-02-08 02:04 UTC, narukaioh commented on src/models/migration/1639308983126-cria_primeiro_migration.ts
> +import { MigrationInterface, QueryRunner } from "typeorm";
Esse arquivo voces podem deletar

2022-02-08 20:21 UTC, nicoledbianchin approved these changes

2022-02-09 17:16 UTC, narukaioh approved these changes

2022-02-10 13:45 UTC, merged