154/envio de email com senha
aceleradora-TW/acelera-mais-api pull request #157
Opened 2022-05-27 16:35 UTC by leonardogomesp

#154 - Envio de email com senha
====
  
### 🆙 CHANGELOG

- Implementa coluna password na model user
- Implementa disparo de email sempre que um mentor é cadastrado
- Implementa função básica para gerar uma senha aleatória

## ⚠️ Me certifico que:

- [ ] Não deixei nenhum novo warning, erro ou console.log nas minhas modificações
- [ ] Fiz deploy para ambiente de teste certificando que o build não quebrou
- [ ] Solicitei **code review** para 2 pessoas
- [ ] Solicitei **QA** para 2 pessoas
- [ ] Obtive aprovação de QA e posso fazer merge

## ⚠️ Como testar:

*Esses passos são apenas exemplos*

- [ ] Fazer deploy em ambiente de teste
- [ ] Abrir URL da aplicação de teste
- [ ] Verificar modificação 1
- [ ] Verificar modificação 2
- [ ] Aplicação não deve conter nenhum erro, warning ou console.log
- [ ] Alteração proposta no card foi implementada

2022-05-27 17:21 UTC, narukaioh requested changes

2022-05-27 17:21 UTC, narukaioh commented on src/service/email/EmailService.ts
> +export const sendEmail = (mentorName, mentorPassword, mentorEmail) => {
Se o nome do arquivo é EmailService, na função deve ser EmailService tb. Outra coisa é respeitar o padrao de projeto que foi definido

const EmailService = () => {

    const send = () => {}
    
    return { send }
    
}

2022-05-27 17:21 UTC, narukaioh commented on src/service/password/PasswordService.ts
> +  return Math.random().toString(36).slice(-10);
Usar o JWT para encriptar a senha de forma segura, pode usar outra secret para isso.

2022-05-27 17:21 UTC, narukaioh commented on src/service/user/UserRequest.ts
> +      password: gerarPassword()
Nao usar nome de funções em portugues

2022-05-27 17:22 UTC, leonardogomesp commented on src/service/email/EmailService.ts
> +export const sendEmail = (mentorName, mentorPassword, mentorEmail) => {
certo, isso passou em branco hehe

2022-05-27 17:23 UTC, leonardogomesp commented on src/service/password/PasswordService.ts
> +  return Math.random().toString(36).slice(-10);
Ok!

2022-05-27 17:23 UTC, leonardogomesp commented on src/service/user/UserRequest.ts
> +      password: gerarPassword()
Ok

2022-05-30 16:12 UTC, narukaioh requested changes

2022-05-30 16:12 UTC, narukaioh commented on package.json
> +    "json-web-token": "^3.2.0",
pq estamos usando essa biblioteca se ja temos "jsonwebtoken" instalado no projeto?

2022-05-30 16:12 UTC, narukaioh commented on src/service/email/EmailService.ts
> +      Olá, ${mentorName}!
Acho que poderiamos inicialmente separar certas coisas do que é responsabilidade de cada função, vejam essa funcão está enorme devido a esse texto fixado ao codigo. Seria interessante que essas informações viessem de um arquivo json ou q ficassem separadas. E um dia quem sabe esse template pode ser salvo no banco de dados

2022-05-31 10:09 UTC, narukaioh commented on src/service/email/EmailService.ts
> +export const sendEmail = (mentorName, mentorPassword, mentorEmail) => {
sem problemas kkkk

2022-05-31 12:21 UTC, yrachid commented on README.md
> +SECRET_PASSWORD=
Além do README, existe algum outro lugar onde essa lista de variáveis deveria ser atualizada?  Não estamos usando nada tipo [dotenv](https://github.com/motdotla/dotenv)? Se não, talvez ele facilite a vida para desenvolver localmente.

2022-05-31 12:22 UTC, yrachid commented on src/controllers/user/index.ts
> +  catch (error) { return response.status(500).json(error) }
Não está relacionado a este PR, mas esse tipo de coisa poderia ser padronizado por alguma ferramenta de formatação de código. De repente vale a pena investigar o quão difícil seria adicionar o [prettier](https://prettier.io/) ao projeto?

2022-05-31 12:25 UTC, yrachid commented on src/service/email/EmailService.ts
> +  const send = (from, subject, email, content) => {
Se estamos usando tipo, talvez essa seria uma oportunidade bacana de explorar o sistema de tipos do typescript:

```suggestion
type EmailPayload = {
  from: string;
  subject: string;
  email: string;
  content: string;
}
  const send = ({from, subject, email, content}: EmailPayload) => {
```

Se não estamos usando tipos, ignorem este comentário completamente.

2022-05-31 12:26 UTC, yrachid commented on src/service/email/EmailService.ts
> +  const send = (from, subject, email, content) => {
Se estamos usando tipo, talvez essa seria uma oportunidade bacana de explorar o sistema de tipos do typescript:
```suggestion
type EmailPayload = {
  from: string;
  subject: string;
  email: string;
  content: string;
}

export const EmailService = () => {
  const send = ({from, subject, email, content}: EmailPayload) => {
```

Se não estamos usando tipos, ignorem este comentário completamente.

2022-05-31 12:30 UTC, leonardogomesp commented on src/service/email/EmailService.ts
> +  const send = (from, subject, email, content) => {
Não estamos utilizando, mas seriam todos strings.

2022-05-31 12:31 UTC, leonardogomesp commented on src/controllers/user/index.ts
> +  catch (error) { return response.status(500).json(error) }
Poderíamos criar um card de débito técnico para investigar isso, o que acha?

2022-05-31 12:37 UTC, leonardogomesp commented on src/service/email/EmailService.ts
> +    let message = {
Message iria ser declarada outra vez, mas mudamos a abordagem

2022-05-31 12:39 UTC, yrachid commented on src/service/email/EmailService.ts
> +    const { NODEMAILER_EMAIL, NODEMAILER_PASSWORD } = process.env
Acho que isso ficaria pra outra PR, mas o que acontece se o ambiente não tiver essas variáveis? Provavelmente o envio de email falhará silenciosamente com um erro difícil de entender (especialmente em ambiente de produção). 

De repente vale à pena abstrair o uso de variáveis de ambiente em um módulo separado que garanta que estas variáveis existam e falhe com um mensagem descritiva caso contrário.

2022-05-31 12:42 UTC, leonardogomesp commented on src/service/email/EmailService.ts
> +    const { NODEMAILER_EMAIL, NODEMAILER_PASSWORD } = process.env
podemos criar um card referente a isso tbm

2022-05-31 13:15 UTC, yrachid commented on README.md
> +NODEMAILER_PASSWORD=VDR1ehc_eha1cgj7bxw
Esse valor é falso ou é o mesmo que será usado em produção? Se for o valor de produção, não deveria ser commitado por questões de segurança.

2022-05-31 13:18 UTC, yrachid commented on src/service/email/EmailService.ts
> +    let transport = nodemailer.createTransport({
```suggestion
    const transport = nodemailer.createTransport({
```

2022-05-31 13:29 UTC, yrachid commented on src/service/email/EmailService.ts
> +  return { send }
A maneira mais simplificada de implementar isso seria externalizar o `nodemailer` em seu próprio módulo e importá-lo aqui:

```suggestion
import {transporter} from './email-transporter'

export const EmailService = () => {
    const message = {
      from: from,
      to: email,
      subject: subject,
      text: content
    }

    try {
      const info = await transporter.sendMail(message)
      console.log('Email sent:', JSON.stringify(info))
    } catch (error) {
      console.error('Failed to send email:', error.message)
    }

  }
  return { send }
```

Uma vantagem aqui seria que `EmailService` fica um pouco mais desacoplado da biblioteca `nodemailer`, ou seja, se um dia vocês precisarem trocar a implementação de envio de emails, o código de `EmailService` não sofreria tanto impacto, bastaria trocar o import.

Enfim, não é uma mudança que precisa ser feita, é só pra levantar a bola e deixar vocês pensando sobre acoplamento, responsabilidades, etc.

2022-05-31 14:58 UTC, narukaioh approved these changes

2022-05-31 15:16 UTC, nicoledbianchin approved these changes

2022-05-31 16:57 UTC, merged