175/Envio de email para candidatas não importadas
aceleradora-TW/acelera-mais-api pull request #179
Opened 2022-06-24 18:55 UTC by leonardogomesp

#175  - Envio de email para candidatas não importadas 
====
  
### 🆙 CHANGELOG

- Muda nome de model responsável por candidatas incompletas
- Implementa service dedicada a candidatas incompletas
- Implementa disparo de email para candidatas incompletas

## ⚠️ Me certifico que:

- [ ] Não deixei nenhum novo warning, erro ou console.log nas minhas modificações
- [ ] Fiz deploy para ambiente de teste certificando que o build não quebrou
- [ ] Solicitei **code review** para 2 pessoas
- [ ] Solicitei **QA** para 2 pessoas
- [ ] Obtive aprovação de QA e posso fazer merge

## ⚠️ Como testar:

- [ ] Abra o link https://leo-acelera-mais-front.herokuapp.com/
- [ ] Faça login utilizando o email leonardogomespadilha@gmail.com e a senha jyql7qm4hx
- [ ] Adicione uma candidata invalida temporária na linha 47 da [planilha de exercicios](https://docs.google.com/spreadsheets/d/13pIgJAPUDk-6OgJ4Ecfm9vCrlzyLLpFp3E25cb-2dF0/edit#gid=549640884)
- [ ] O email deverá ser válido para que possa receber a mensagem
- [ ] Crie um novo processo seletivo
- [ ] Realize o import da planilha de candidatas
- [ ] Realize o import da planilha de exercicios
- [ ] Verifique se o email foi recebido
- [ ] Aplicação não deve conter nenhum erro, warning ou console.log
- [ ] Alteração proposta no card foi implementada

2022-06-24 19:28 UTC, narukaioh commented on src/service/email/EmailService.ts
> +  const sendNegativeEmail = (email, name, message) => {
Nossa senhora hahaha temos 3 funções de email?
basta apenas uma "sendEmail" qualquer mensagem que enviarmos apenas essa fará o serviço de entrega, quem define o conteudo é quem utiliza EmailService, como tinhamos conversado

2022-06-27 17:37 UTC, leonardogomesp commented on src/service/email/EmailService.ts
> +  const sendNegativeEmail = (email, name, message) => {
refatoração feita!

2022-06-27 18:08 UTC, narukaioh requested changes

2022-06-27 19:05 UTC, narukaioh requested changes

2022-06-27 19:05 UTC, narukaioh approved these changes

2022-06-27 20:28 UTC, nicoledbianchin approved these changes

2022-06-28 17:26 UTC, merged