182/email nao esta sendo chave unica
aceleradora-TW/acelera-mais-api pull request #195
Opened 2022-07-14 17:14 UTC by ErickCardoso007

#182 - email nao esta sendo chave unica
====
  
### 🆙 CHANGELOG

- impede o cadastramento de mentoras caso o e-mail se repita. (referente a um email de uma mentora já cadastrada)

## ⚠️ Me certifico que:

- [ ] Não deixei nenhum novo warning, erro ou console.log nas minhas modificações
- [ ] Fiz deploy para ambiente de teste certificando que o build não quebrou
- [ ] Solicitei **code review** para 2 pessoas
- [ ] Solicitei **QA** para 2 pessoas
- [ ] Obtive aprovação de QA e posso fazer merge

## ⚠️ Como testar:

*Esses passos são apenas exemplos*

- [ ] Abra o postman
- [ ] Insira a URL https://erick-acelera-mais-api.herokuapp.com/user 
- [ ] crie um usuário: 
![image](https://user-images.githubusercontent.com/88493966/179038098-8ba07ccc-33c6-4a06-a405-2c6618fe3b00.png)
- [ ] faça um post e observe o terminal do postman exibir "Email enviado com sucesso!"
- [ ] faça post novamente, dessa vez deve aparecer "User already exist in database" no terminal do postman
- [ ] Aplicação não deve conter nenhum erro, warning ou console.log
- [ ] Alteração proposta no card foi implementada

2022-07-14 17:21 UTC, leonardogomesp requested changes

2022-07-14 17:44 UTC, ErickCardoso007 commented on src/routes.ts
> -  app.get("/user", verifyAccessToken, getUser)
Alterado.

2022-07-14 17:59 UTC, leonardogomesp commented on src/models/entity/User.ts
> +  JoinColumn,
os imports das linhas 5, 6, 7 e 8 não estão sendo utilizadas, o que acha de retirarmos? 

apenas um sugestão, não é nada que gere impedimento deste PR

2022-07-14 17:59 UTC, leonardogomesp approved these changes

2022-07-14 18:26 UTC, leonardogomesp approved these changes

2022-07-15 12:43 UTC, leonardogomesp approved these changes

2022-07-18 14:06 UTC, nicoledbianchin approved these changes

2022-07-18 14:20 UTC, merged