fix(controllers/userx): remoção de password da data
aceleradora-TW/acelera-mais-api pull request #211
Opened 2022-10-06 17:45 UTC by Renatu5

#202 - Dados desnecessarios no login
====
 
## ⚠️ Me certifico que:

- [ ] Não deixei nenhum novo warning, erro ou console.log nas minhas modificações
- [ ] Fiz deploy para ambiente de teste certificando que o build não quebrou
- [ ] Solicitei **code review** para 2 pessoas
- [ ] Solicitei **QA** para 2 pessoas
- [ ] Obtive aprovação de QA e posso fazer merge

## ⚠️ Como testar:

*Esses passos são apenas exemplos*

- [ ] acesse https://renato-acelera-mais-front.herokuapp.com/
- [ ] Entre com os seguintes dados:
   - email: teste2@email.com
   - senha: kw4nxt1qbj
- [ ] abra o "inspecionar elemento" e vá em "rede" ou "network" caso esteja em inglês
![image](https://user-images.githubusercontent.com/97472730/194382420-3258b5c9-e048-4c9c-a812-6c13eb809f0c.png)
- [ ] acesse o gerenciamento de mentoras
- [ ] selecione a opção "FETCH/XHR", e abra o payload "user"
![image](https://user-images.githubusercontent.com/97472730/194382586-cfe20f0f-bf3c-441b-8b84-b28b9a5e3cdc.png)
![image](https://user-images.githubusercontent.com/97472730/194381945-cbe3cd69-0748-4011-95a5-99bf69290883.png)
- [ ] não deve aparecer o campo "password" nos usuários cadastrados
- [ ] Aplicação não deve conter nenhum erro, warning ou console.log
- [ ] Alteração proposta no card foi implementada

2022-10-07 10:22 UTC, narukaioh requested changes

2022-10-07 10:22 UTC, narukaioh commented on src/controllers/userx/index.ts
> -    const result = await userService(request).getAllUser()
Nao é nesse momento que devemos fazer isso. A forma correta é fazer isso em uma camada mais profunda.

Usamos em **getAllUser** uma função da service **userService** que é chamada nessa linha, tem a função de buscar no banco todos os **users** com seus campos incluindo o campo **password**.

Quando interagimos dessa forma com os dados, estamos conversando com o banco. E essa conversação é mediada pelo framework **typeORM**

Entao, dessa forma, a gente consegue pedir para o banco atraves do typeORM que ele nos passe todos os dados de um recurso  com aqueles campos específicos.

2022-10-07 10:24 UTC, narukaioh commented
Lembrem-se de marcar as tasks propostas no PR. Para identificarmos se vocês fizeram as avaliações na app

2022-10-11 13:44 UTC, narukaioh approved these changes

2022-10-11 13:52 UTC, janinelps approved these changes

2022-10-11 16:06 UTC, merged