213/salvar senha md5
aceleradora-TW/acelera-mais-api pull request #218
Opened 2022-10-18 17:02 UTC by MarquesEmiLly

#213 - Salvar senha md5
====
  
### 🆙 CHANGELOG

*Mudanças *

1 - A encriptação JWT na ação de salvar senhas foi substituida pelo md5 
2 - Funcionalidades de envio de email com a senha desincriptada 
3 - Geração de uma nova senha para reenvo de email

## ⚠️ Me certifico que:

- [x] Não deixei nenhum novo warning, erro ou console.log nas minhas modificações
- [x] Fiz deploy para ambiente de teste certificando que o build não quebrou
- [x] Solicitei **code review** para 2 pessoas
- [x] Solicitei **QA** para 2 pessoas
- [x] Obtive aprovação de QA e posso fazer merge

## ⚠️ Como testar:

- [x] https://jean-acelera-mais-api.herokuapp.com/
- [x] Abrir URL da aplicação de teste
- [x] Criar um usuário no Postman usando o token ( eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4ifQ.YQ0DMllL22T82tEo2saPmqVDiYIYwiNxY2VMzH53tW8 )
- [x] Verificar se recebeu email com senha  
- [x] Verificar se o usuário foi salvo com a flag first-login e senha encriptada com md5 no Postman
- [x] Fazer login com  o usuário criado 
- [x] Verificar se retorna um token válido 
- [x] Reenviar email pelo Postman fazendo um put no endpoit " https://jean-acelera-mais-api.herokuapp.com/user/id/email_verification "
- [x] Verificar se o novo email foi recebido com a nova senha
- [x] Verificar se o usuário foi salvo com a flag email-resent e senha encriptada com md5
- [x] Mudar a senha do usuario criado com um put no endpoint user 
- [x] Verificar se a senha foi alterada e o status do usuario mudou para user-enable
- [x] Aplicação não deve conter nenhum erro, warning ou console.log
- [x] Alteração proposta no card foi implementada

2022-10-18 18:03 UTC, narukaioh requested changes

2022-10-18 18:03 UTC, narukaioh commented on src/service/user-service/user-request.ts
> +    generatePassword,
pq generatePassword precisa ser retornada?

2022-10-18 18:03 UTC, narukaioh commented on src/service/user-service/user-service.ts
> -    const user = UserRequest(request).getUserForResendEmail()
Nessa logica, deixamos como responsabilidade para getUserForResendEmail a criação da senha. Não devemos trazer para "resendEmail" a responsabilidade de gerar a senha. Como esta sendo feita na linha 26 a diante

2022-10-18 18:17 UTC, JeanCastilhos2 commented on src/messages/email/content.ts
> +    const { name, password } = emailUser
O intuito da nomeação como "emailUser" seria declarar a variável de usuário para envio do e-mail, mas realmente ficou confuso

2022-10-19 17:52 UTC, narukaioh approved these changes

2022-10-19 19:00 UTC, janinelps approved these changes

2022-10-21 12:35 UTC, merged