216/feat gerar link de convite mentora avaliadora
aceleradora-TW/acelera-mais-api pull request #222
Opened 2022-10-25 14:41 UTC by EnzoSoares-dev

#216- Listagem de mentora avaliadora: gerar link de convite
====
  
### 🆙 CHANGELOG

- Foi criado uma nova modal presente na pagina de listagem de mentoras, responsável por gerar o link de acesso para novas mentoras. Ele está presente no arquivo src/pages/user/index.js
- Essa modal possui um componente que gera uma requisição para o back-end pedindo um token com tempo de vida estimado de 30 minutos
- Foi criado uma rota que possui uma variável para o token gerado no back-end. Ela esta presente em src/routes/index.js
- Ao acessar o link gerado, será realizada outra requisição ao back-end, comparando se o tempo de vida ainda está válido ou não.
- Se este for válido será apresentado o formulário de cadastro dentro de src/pages/user/forms/user/record
- Caso contrário, ele apresentará uma mensagem de erro falando que o tempo de vida do link expirou e pede para requerir um novo.

## ⚠️ Me certifico que:

- [x] Não deixei nenhum novo warning, erro ou console.log nas minhas modificações
- [x] Fiz deploy para ambiente de teste certificando que o build não quebrou
- [x] Solicitei **code review** para 2 pessoas
- [ ] Solicitei **QA** para 2 pessoas
- [ ] Obtive aprovação de QA e posso fazer merge

## ⚠️ Como testar:

- [x] Iniciar o back-end acessando o link: http://enzo-acelera-mais-api.herokuapp.com/
- [x] Acessar o front-end com a seguinte URL: http://enzo-acelera-mais.herokuapp.com/
- [x] Realizar o login utilizando o seguinte email: 'soaressenzo@gmail.com' com a senha '123456'
- [x] Acessar o botão "Gerenciar mentoras"
- [x] Clicar no botão "Gerar Convite"
- [x] Copiar o link gerado na modal clicando em "Copiar"
- [x] Abrir uma nova guia no navegador e colar o link
- [x] Clicar em Ok no alert que aparecer
- [x] Deve aparecer um formulário de cadastro
- [x] Ao aguardar 30 minutos, deve-se recarregar a página
- [x] Ao recarregar, deve aparecer uma mensagem de erro
- [x] Aplicação não deve conter nenhum erro, warning ou console.log
- [x] Alteração proposta no card foi implementada

2022-10-25 14:57 UTC, narukaioh requested changes

2022-10-25 14:57 UTC, narukaioh commented on src/controllers/userx/link/index.ts
> +      "user/" + JWT.sign({ date: new Date().valueOf() }, process.env.SECRET),
Para criar um link baseado em tempo de expiração, devemos usar a logica de "expiresIn", conversem com o Jean ele ta adicionado um tempo de expiração ao token de login.

2022-10-25 14:57 UTC, narukaioh commented on src/controllers/userx/link/index.ts
> +      return time / (1000 * 60) < 30 ? true : false
Dessa forma, essa validação nao é necessária, pois o JWT tem as ferramentas corretas para validar um token, evita de fazer essa matemática e tornaria o codigo mais simples também

2022-10-25 14:57 UTC, narukaioh commented on src/controllers/userx/link/index.ts
> +      "user/" + JWT.sign({ date: new Date().valueOf() }, process.env.SECRET),
Outra coisa importante. Vamos usar mais a interpolação invés da concatenação

\`user/${token}\` >>> "user/" + token

2022-10-27 16:57 UTC, janinelps approved these changes

2022-11-01 13:42 UTC, narukaioh approved these changes

2022-11-01 15:00 UTC, merged