243/lista mentoras pesquisa
aceleradora-TW/acelera-mais-api pull request #245
Opened 2022-12-05 16:50 UTC by janinelps

# 243-lista-mentoras-pesquisa
====
  
### 🆙 CHANGELOG

*Esses passos são apenas exemplos*

- Mudança 1
- Mudança 2
- Mudança 3

## ⚠️ Me certifico que:

- [ ] Não deixei nenhum novo warning, erro ou console.log nas minhas modificações
- [ ] Fiz deploy para ambiente de teste certificando que o build não quebrou
- [ ] Solicitei **code review** para 2 pessoas
- [ ] Solicitei **QA** para 2 pessoas
- [ ] Obtive aprovação de QA e posso fazer merge

## ⚠️ Como testar:

*Esses passos são apenas exemplos*

- [ ] Fazer deploy em ambiente de teste
- [ ] Abrir URL da aplicação de teste
- [ ] Verificar modificação 1
- [ ] Verificar modificação 2
- [ ] Aplicação não deve conter nenhum erro, warning ou console.log
- [ ] Alteração proposta no card foi implementada

2022-12-05 17:43 UTC, narukaioh requested changes

2022-12-05 17:43 UTC, narukaioh commented on src/service/user-service/user-service.ts
> +    if (search != "") {
```javascript
let where = {} 
if (search) { 
    where = { name: Like(`%${search}%`)
}
```

vamo evitar fazer if em cima de try catch, esse if precisa ser dentro

2022-12-08 14:42 UTC, gabrielapsgomes approved these changes

2022-12-08 14:44 UTC, gabrielapsgomes approved these changes

2022-12-09 13:47 UTC, narukaioh approved these changes

2022-12-09 18:52 UTC, narukaioh approved these changes

2022-12-12 13:02 UTC, merged