50/editar avaliacao do desafio
aceleradora-TW/acelera-mais-api pull request #66
Opened 2021-11-22 14:11 UTC by inglyd

#<NUMERO-DO-CARD> - Titulo do Card
====
  
### 🆙 CHANGELOG

*Esses passos são apenas exemplos*

- Mudança 1
- Mudança 2
- Mudança 3

## ⚠️ Me certifico que:

- [x] Não deixei nenhum novo warning, erro ou console.log nas minhas modificações
- [x] Fiz deploy para ambiente de teste certificando que o build não quebrou
- [ ] Solicitei **code review** para 2 pessoas
- [ ] Solicitei **QA** para 2 pessoas
- [ ] Obtive aprovação de QA e posso fazer merge

## ⚠️ Como testar:

*Esses passos são apenas exemplos*

- [ ] Fazer deploy em ambiente de teste
- [ ] Abrir URL da aplicação de teste
- [ ] Verificar modificação 1
- [ ] Verificar modificação 2
- [ ] Aplicação não deve conter nenhum erro, warning ou console.log
- [ ] Alteração proposta no card foi implementada

2021-11-22 15:36 UTC, narukaioh requested changes

2021-11-22 15:36 UTC, narukaioh commented on src/service/exercise/EvaluationRequest.ts
> +/* eslint-disable space-before-function-paren */
remover esse comentário e ajustar o problema, é apenas um erro de formatação do código. O auto-save deveria resolver

2021-11-22 15:36 UTC, narukaioh commented on src/service/exercise/EvaluationService.ts
> +/* eslint-disable space-before-function-paren */
mesma coisa para esse comentário tb, remover e formatar o codigo

2021-11-22 16:05 UTC, ldiasrs commented on src/controllers/exercise/index.ts
> +    await evaluationRepository.update(request.params.id, evaluation)
No futuro poderíamos pensar em refatorar e essas funções de validate e update para uma função de serviço o que acha? assim o código ficaria mais modular e menos acoplado com o controller, pequenas partes com pequenas responsabilidades promovem a reutilização e melhor leitura ;)

2021-11-22 16:31 UTC, Jojorel commented on src/service/exercise/EvaluationService.ts
> +/* eslint-disable space-before-function-paren */
Fizemos as mudanças.

2021-11-22 16:31 UTC, Jojorel commented on src/service/exercise/EvaluationRequest.ts
> +/* eslint-disable space-before-function-paren */
Fizemos as mudanças.

2021-11-22 17:38 UTC, narukaioh approved these changes

2021-11-23 12:46 UTC, ldiasrs approved these changes
Podemos seguir com esse PR e sugiro criar outro para melhoria em camadas

2021-11-23 16:28 UTC, merged