feat: organização dos relacionamentos entre as tabelas
aceleradora-TW/acelera-mais-api pull request #95
Opened 2021-12-12 13:49 UTC by narukaioh

### 🆙 CHANGELOG

Foi adicionado nesse PR uma resolução para o nosso problema de relacionamento entre as tabelass de exercise, candidate e evaluation. Nesse PR eu consegui juntar todas as informações de candidatas, nota e exercício em apenas uma resposta nos endpoints **GET /exercise** e **GET /exercise/:id**

## ⚠️ Me certifico que:

- [x] Não deixei nenhum novo warning, erro ou console.log nas minhas modificações
- [x] Fiz deploy para ambiente de teste certificando que o build não quebrou
- [ ] Solicitei **code review** para 2 pessoas
- [ ] Solicitei **QA** para 2 pessoas
- [ ] Obtive aprovação de QA e posso fazer merge

## ⚠️ Como testar:

*Esses passos são apenas exemplos*

- [ ] Abrir o postman, 
- [ ] Use essa URL base para as operações seguintes (https://ju-acelera-mais-api.herokuapp.com/hiring_process)
- [ ] Criar um novo hiring_process - **POST /hiring_process**
- [ ] Copiar o ID do hiring_process criado e utilizar no proximo passo
- [ ] Importar candidatas - **POST /candidate/hiring_process/:id**
- [ ] Importar desafios - **POST /exercise/hiring_process/:id**
- [ ] Listar desafios - **GET /exercise**
- [ ] Ao listar os desafios, voce deverá receber uma lista de exercicios
- [ ] Escolha qualquer desafio e verifique se nesse contem os dados da **candidate, hiring-process e evaluation**

2021-12-13 12:55 UTC, patriciatersariol requested changes

2021-12-13 12:55 UTC, patriciatersariol commented on src/models/entity/Candidate.ts
> +  @JoinColumn({ name: 'exericse_id' })
o nome 'exercise_id' está com erro de digitação

2021-12-13 13:01 UTC, narukaioh commented on src/models/entity/Candidate.ts
> +  @JoinColumn({ name: 'exericse_id' })
consertei

2021-12-14 13:02 UTC, ldiasrs approved these changes
Muito nom

2021-12-14 13:02 UTC, ldiasrs commented on src/controllers/candidate/index.ts
> +  const { id } = request.params
Depois se não der trabalho poderiamos migrar essa logica para dentro de um serviço o que acha? Posso fazer nesse PR tambem se tu quiser ;)

2021-12-14 15:19 UTC, narukaioh commented on src/controllers/candidate/index.ts
> +  const { id } = request.params
Esse PR não vai ir pra frente, mas deixei la nos avisos pra mentoria abrir cards de débito técnico sobre qualquer sugestão pra gente não bloquear as alunas essa penultima semana

2021-12-14 16:54 UTC, merged